name: diff
description: diff
inputs:
    subdir:
        description: Find diff directory
        required: true
outputs:
    diff-count:
        description: diff line count
        value: ${{ steps.diff.outputs.diff-count }}
runs:
    using: composite
    steps:
        - id: diff
          env:
              HEAD_BRANCH: ${{ github.head_ref }}
              TARGET_BRANCH: ${{ github.base_ref }}
          run: |
              git fetch origin ${TARGET_BRANCH}
              git fetch origin ${HEAD_BRANCH}
              count=`git diff origin/${TARGET_BRANCH} ${HEAD_BRANCH} --name-only --relative=${{ inputs.subdir }} | wc -l`
              echo "::set-output name=diff-count::$(echo $count)"
          shell: bash
