name: Build Test

on:
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
    ts-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  cache: npm
            - name: Install deps
              run: npm i
            - name: Set env
              run: export DATABASE_URL="file:./dev.db"
            - name: migrate DB
              run: npm run prisma:migrate
            - name: Build
              run: npm run build
