name: Check Package

on:
    pull_request:
        types: [opened]
    workflow_dispatch:

jobs:
    npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - uses: MeilCli/npm-update-check-action@v2
              id: outdated
            - uses: thollander/actions-comment-pull-request@v2
              if: steps.outdated.outputs.has_npm_update != 'false'
              with:
                  message: 'Please update npm packages'
