name: Check Package

on:
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
    npm:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - uses: MeilCli/npm-update-check-action@v2
              id: outdated
            - uses: thollander/actions-comment-pull-request@v2
              if: steps.outdated.outputs.has_npm_update != 'false'
              with:
                  message: format("パッケージ名 ", ${{ steps.outdated.outputs.npm_update_json.name }}, "\n現在のバージョン ", ${{ steps.outdated.outputs.npm_update_json.current }}, "\n最新のバージョン ", ${{ steps.outdated.outputs.npm_update_json.latest }})
